# 工作流的名称
name: React CI/CD Pipeline

# 触发工作流的事件
on:
  push:
    branches: [ "main" ] # 当推送到 main 分支时触发
  pull_request:
    branches: [ "main" ] # 当向 main 分支发起 Pull Request 时触发

# 定义一个或多个作业 (job)
jobs:
  # 作业的唯一 ID
  lint-check:
    # 作业的名称（显示在 GitHub UI 上）
    name: Lint Check
    # 作业运行的虚拟机环境
    runs-on: ubuntu-latest

    # 作业中的一系列步骤 (step)
    steps:
      # 第一步：检出代码
      # 使用官方的 actions/checkout action 来获取你的仓库代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 第二步：设置 Node.js 环境
      # 使用官方的 actions/setup-node action 来安装指定版本的 Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # 指定 Node.js 版本
          cache: 'npm'       # 缓存 npm 的依赖包，加快后续构建速度

      # 第三步：安装依赖
      # 使用 npm ci 而不是 npm install，它更快、更可靠，专门用于自动化环境
      - name: Install dependencies
        run: npm ci

      # 第四步：运行 ESLint
      - name: Run ESLint
        run: npm run lint
